### ISSUE TITLE
Improving the Unicode Blocker

### ISSUE THREAD

**Issue by xqwtxon** [ReinfyTeam/ProfanityFilter#14]
**Here's my replacement for the blocking of unicode characters...**

https://github.com/ReinfyTeam/ProfanityFilter/blob/4a66ec38dbb24430fc9526b7829e27c50081ec0f/src/PluginAPI.php#L65-L161

**Replace more characters for blocking unicode...**

**Comment by Reinfy** [comment]
You should **remove** these following lines:
https://github.com/ReinfyTeam/ProfanityFilter/blob/4a66ec38dbb24430fc9526b7829e27c50081ec0f/src/PluginAPI.php#L157-L158

What if there's emojis implemented to the server. You should remove this, because we only blocking **non-printable ascii characters.**

**Comment by xqwtxon** [comment]
Yes, we do... So, we ask when unicode characters should blocked on the configuration.

**Comment by Reinfy** [comment]
Closing this as https://github.com/ReinfyTeam/ProfanityFilter/pull/32 pull request.
